apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  labels:
    app: backend-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: backend-api